### ISSUE TITLE
예약 가능 시간 관련

### ISSUE THREAD

**Issue by lovelyunsh** [LSW990918/ConcurrencyControlProject#1]
## 예약 가능 시간
현재 예약 가능한 시간에 관련해서 논의가 필요합니다.

erd 상으로 bookabledate가 있는데,
이 시간까지 예약이 가능한 것으로 설정 하였는데,
예약 가능에 대한 시작시간은 어떻게 설정할 지 논의가 필요합니다.

가능한 방법으로
1. 생성이 된 시점부터 bookabledate까지 예약이 가능.
2. 새로운 startdate를 추가하여 그 사이의 시간만 예약이 가능.

많은 의견 바랍니다.

**Comment by soang94** [comment]
1번이 좋은거 같습니다

**Comment by LSW990918** [comment]
createdAt < 예약가능시간 < bookableDate

저도 1번이 좋은것 같습니다
