### ISSUE TITLE
날짜 포맷 통일

### ISSUE THREAD

**Issue by lovelyunsh** [LSW990918/ConcurrencyControlProject#20]
## 주제
현재 상품 데이터 create를 위해 날짜 데이터를 받으며
validation과 localdatetime으로 형 변환을 위해 포맷을 통일해서 정했으면 합니다.

## 제안
`yyyy-MM-dd HH:mm:ss`

우선 적용한 포맷은 위 형태로 진행 중입니다.
다른 의견 있으시면 코멘트 남겨주시기 바랍니다.

**Comment by LSW990918** [comment]
지금 봐서는 Date를 직접 입력하는 곳은 Goods 쪽 밖에 없는것 같습니다.

우선 위 형태로 진행해도 될 것 같습니다.
