### ISSUE TITLE
GlobalExceptionHandler 추가 필요

### ISSUE THREAD

**Issue by lovelyunsh** [LSW990918/ConcurrencyControlProject#21]
## 주제
기본적인 CRUD 제작에 있어서도 Exception 처리를 위해 GlobalExceptionHandler가 필요할 것 같습니다.

## 제안
현재 패키지 구조 상
common/exception 하위로 두는 것이 좋을 것 같습니다.
다른 의견 있으시면 코멘트 남겨주세요.

시간 남으시는 분이 이 이슈의 assignees를 본인으로 변경하고 
feature/global-exception branch 파서 작업해주시면 좋을 것 같습니다.

**Comment by LSW990918** [comment]
이부분은 제가 기본적으로 몇개 추가해놓고 풀리퀘 올리겠습니다.

**Comment by soang94** [comment]
저는 common/exception 해서 만들어놨는데 어떻게 할까요

**Comment by LSW990918** [comment]
그렇다면 이부분은 승상님께 양도하겠습니다.
저는 이어서 티켓부분 하도록 하죠!

**Comment by soang94** [comment]
확인했습니다 #16 이슈 하면서 pr올릴게요~
